name: Generate contributions

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: pip install requests

      - name: Generate contributions
        run: python ./.github/contributions.py
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: deploy
        run: |
          git config --global user.name "$user_name"
          git config --global user.email "$user_email"
          git init
          git add -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push -f https://_:"$token"@github.com/"$repository".git "$ref_name":"$ref_name"
        shell: bash
        env:
          repository: ${{ github.repository }}
          ref_name: master
          token: ${{ secrets.GITHUB_TOKEN }}
          user_name: GitHub Action
          user_email: action@github.com
          cname: none
