name: Generate contributions

on: [push]

jobs:
  contribute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: deploy
        run: |
          git config --global user.name "$user_name"
          git config --global user.email "$user_email"
          git init
          git add -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push -f https://_:"$token"@github.com/"$repository".git "$ref_name":"$ref_name"
        shell: bash
        env:
          repository: ${{ github.repository }}
          ref_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          user_name: GitHub Action
          user_email: action@github.com
          cname: none
